name: Test CPU Operations

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - run: echo "Running CHIP-8 Operation Tests..."
      - uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          # Version of the zig compiler to use (must be 0.3.0 or up)
          version: master
      - run: zig build test
      
    
